'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Dep_App.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property advancedsettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("advancedsettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Approval_B_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Approval_B-128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property big_peso_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("big-peso-sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_check_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button-check_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_rotate_cw_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button-rotate-cw_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cloudy_sky_plain_wallpaper_for_ipad_2_1024x768_ipad_2_wallpaper_170() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloudy-sky-plain-wallpaper-for-ipad-2,1024x768,ipad-2-wallpaper,170", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Community_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Community Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gnome_mime_application_vnd_lotus_1_2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gnome-mime-application-vnd.lotus-1-2-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Green_bkgd_72rgb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_bkgd_72rgb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Green_bkgd_72rgb11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_bkgd_72rgb11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_network_widescreen_wallpaper_51558() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_network_widescreen_wallpaper_51558", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logos_texts_icons_amp_wallpapers_2green_pack_icon_sujet_41938_1htm_1920x1200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logos-texts-icons-amp-wallpapers-2green-pack-icon-sujet-41938-1htm-1920x1200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pay_payment_money_wallet_creditcard_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pay_payment_money_wallet_creditcard-128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play-r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preferences_desktop_notification() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences-desktop-notification", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preferences_desktop_notification2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences-desktop-notification2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preferences_system_time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences-system-time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preferences_system_time1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences-system-time1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer_basic_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer_basic_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rdms_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rdms logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_basic_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_basic_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property technical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("technical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property username() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("username", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property username1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("username1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property username2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("username2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property x_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
