#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tech.Resource", IsApplication=true)]

namespace Tech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int petc_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tasks_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_custom_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Go_up = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int localtion2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int location = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int panel_border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pcmeal_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sms = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int upload = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Upload2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int view = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Zoom = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int btnCaptureImage = 2131230732;
			
			// aapt resource value: 0x7f08001e
			public const int btnCheckConnection = 2131230750;
			
			// aapt resource value: 0x7f080036
			public const int btnCheckCoordinates = 2131230774;
			
			// aapt resource value: 0x7f080024
			public const int btnCheckGPS = 2131230756;
			
			// aapt resource value: 0x7f080008
			public const int btnDateDeployment = 2131230728;
			
			// aapt resource value: 0x7f080020
			public const int btnGPS = 2131230752;
			
			// aapt resource value: 0x7f080014
			public const int btnGetAddress = 2131230740;
			
			// aapt resource value: 0x7f080023
			public const int btnM_CheckConnection = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int btnM_NewDeployment = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int btnM_ViewDeployment = 2131230754;
			
			// aapt resource value: 0x7f080016
			public const int btnMaps = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int btnNewDeployment = 2131230748;
			
			// aapt resource value: 0x7f08002d
			public const int btnRegister = 2131230765;
			
			// aapt resource value: 0x7f08000f
			public const int btnSaveDeployment = 2131230735;
			
			// aapt resource value: 0x7f080038
			public const int btnShowListDeployment = 2131230776;
			
			// aapt resource value: 0x7f080025
			public const int btnSignUp = 2131230757;
			
			// aapt resource value: 0x7f080037
			public const int btnUploadDeployment = 2131230775;
			
			// aapt resource value: 0x7f08001b
			public const int btnUpload_Deployment = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int btnViewDeployments = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int btnViewDetailed_Deployment = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int button1 = 2131230751;
			
			// aapt resource value: 0x7f080027
			public const int editText1 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int editText2 = 2131230760;
			
			// aapt resource value: 0x7f08000a
			public const int imageView1 = 2131230730;
			
			// aapt resource value: 0x7f080030
			public const int img_ViewTech = 2131230768;
			
			// aapt resource value: 0x7f080011
			public const int latitude = 2131230737;
			
			// aapt resource value: 0x7f080034
			public const int lblCoordinates = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int lblDate_Deployment = 2131230771;
			
			// aapt resource value: 0x7f080031
			public const int lblPETC = 2131230769;
			
			// aapt resource value: 0x7f080035
			public const int lblTask_Description = 2131230773;
			
			// aapt resource value: 0x7f080032
			public const int lblTasks = 2131230770;
			
			// aapt resource value: 0x7f08002f
			public const int lblTotalNotUploaded = 2131230767;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout2 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout3 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout4 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout5 = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout6 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout7 = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout8 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout9 = 2131230734;
			
			// aapt resource value: 0x7f08002e
			public const int listView1 = 2131230766;
			
			// aapt resource value: 0x7f080012
			public const int longitude = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int myButton = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int provider = 2131230739;
			
			// aapt resource value: 0x7f080026
			public const int relativeLayout1 = 2131230758;
			
			// aapt resource value: 0x7f080002
			public const int spn_PETC = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int spn_Tasks = 2131230724;
			
			// aapt resource value: 0x7f080017
			public const int textView1 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int textView2 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int textView3 = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int txtAddress = 2131230741;
			
			// aapt resource value: 0x7f080029
			public const int txtFullname = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int txtMobileNo = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int txtSerialcode = 2131230764;
			
			// aapt resource value: 0x7f080006
			public const int txtTasksDescription = 2131230726;
			
			// aapt resource value: 0x7f08002a
			public const int txtUsername = 2131230762;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Deployment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GPS = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int List_Deployment_Temp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignIn = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SignUp = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewDeployment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ViewDeployment_Detailed = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int petc_prompt = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int tasks_prompt = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
